# TESTING

In [1]:
from LGPT import PTReplicaMetaBase
from PTReplica import BasicModel

import copy
import numpy as np

In [2]:
import torch

Making small Training Data

In [3]:
train = torch.tensor([[1,2,3,10],[4,5,6,10],[7,8,9,10],[11,12,13,10],[14,15,16,10]], dtype = torch.float)
test = torch.tensor([[17,18,19,10],[20,21,22,10],[23,24,25,10]], dtype = torch.float)

In [4]:
train

tensor([[ 1.,  2.,  3., 10.],
        [ 4.,  5.,  6., 10.],
        [ 7.,  8.,  9., 10.],
        [11., 12., 13., 10.],
        [14., 15., 16., 10.]])

In [5]:
test

tensor([[17., 18., 19., 10.],
        [20., 21., 22., 10.],
        [23., 24., 25., 10.]])

In [6]:
obj = BasicModel(3,5,1,20000,0.6,700,True,0.5,train,test,0.001,0.025)

In [7]:
obj.GiveMeTheLoss()

tensor(101.0318, grad_fn=<MseLossBackward>)

In [8]:
misclist = obj.ProposeMiscParameters()
misclist

[array([1.39311921]), array([4.02739278]), 25, 0, 0]

In [9]:
paramlist = []
for param in obj.Model.parameters():
    paramlist.append(param.clone())

In [10]:
paramlist

[tensor([[-0.0232,  0.4645,  0.5606],
         [-0.0722,  0.0759, -0.1315],
         [-0.0883, -0.2177,  0.4563],
         [ 0.5104,  0.1203,  0.3230],
         [ 0.1458,  0.4790,  0.3175]], grad_fn=<CloneBackward>),
 tensor([ 0.1046, -0.4929, -0.4071,  0.3203, -0.0728], grad_fn=<CloneBackward>),
 tensor([[ 0.3903,  0.3653,  0.2202, -0.3281, -0.1161]],
        grad_fn=<CloneBackward>),
 tensor([-0.2410], grad_fn=<CloneBackward>)]

In [11]:
obj.SumTheSquareWeights(paramlist)

Sum of squares of the weights:  tensor(2.5942)


tensor(2.5942)

In [12]:
obj.PriorLikelihood(misclist, paramlist)

Sum of squares of the weights:  tensor(2.5942)
logprob_part1:  tensor(-55.6762)
logprob_part2:  [1.39311921]


(tensor([-57.0693], dtype=torch.float64), [None])

In [ ]:
Samples, accepts = obj.Runner()
print(accepts)

## Not showing above's output cause it's large. :)

In [14]:
Samples[0]

{'0.weight': tensor([[-0.0696,  0.4344,  0.5595],
         [-0.0914,  0.0888, -0.1211],
         [-0.0934, -0.2502,  0.4802],
         [ 0.4763,  0.1254,  0.3631],
         [ 0.1140,  0.4516,  0.2976]], dtype=torch.float64),
 '0.bias': tensor([ 0.1252, -0.4840, -0.3932,  0.3156, -0.0615], dtype=torch.float64),
 '2.weight': tensor([[ 0.3757,  0.3531,  0.2324, -0.3094, -0.0939]], dtype=torch.float64),
 '2.bias': tensor([-0.2334], dtype=torch.float64)}

In [15]:
Samples[1]

{'0.weight': tensor([[-1.4432e-01, -4.5193e-01,  1.7975e-01],
         [ 2.1833e-01, -1.9691e-02,  4.6423e-01],
         [ 5.3463e-01,  3.9423e-01,  5.2723e-04],
         [ 5.4796e-01,  4.1294e-01,  4.7753e-01],
         [-5.0680e-01, -5.0997e-01,  4.4397e-01],
         [ 3.4782e-01, -3.0222e-01, -1.3735e-01],
         [ 3.5434e-01, -4.2677e-01,  2.9803e-01],
         [-4.1536e-01, -2.2093e-01,  4.0752e-01],
         [ 1.1374e-01,  3.0748e-01,  1.1178e-01],
         [-8.1119e-02, -1.4849e-01,  4.2945e-01],
         [ 3.5091e-02, -2.3392e-01, -1.3645e-01],
         [-5.6785e-01,  9.8233e-02,  1.5259e-01],
         [ 3.1369e-01, -2.0974e-01, -8.6712e-02],
         [-3.5560e-02, -1.8815e-01, -4.4735e-01],
         [-5.4250e-01, -4.3838e-01, -2.6480e-01],
         [ 4.5606e-01,  5.9339e-01, -4.5582e-01],
         [ 5.4662e-01, -4.4814e-01,  4.6402e-01],
         [ 4.9539e-01, -2.8447e-01,  5.4138e-01],
         [ 6.0224e-02,  6.1831e-02,  7.9445e-02],
         [ 3.9757e-01,  1.5372e-01,  4